// Firebase Configuration - Compat SDK
// Generated by Firebase Console for Mahami App

const firebaseConfig = {
  apiKey: "AIzaSyCwRIuqlNUi7mfL5kWf_8pNcRkG4xKa_IQ",
  authDomain: "mahami-app-b75f8.firebaseapp.com",
  projectId: "mahami-app-b75f8",
  storageBucket: "mahami-app-b75f8.firebasestorage.app",
  messagingSenderId: "367991590064",
  appId: "1:367991590064:web:878a51ff999998cb617f75",
  measurementId: "G-V4KHGQ3EGY"
};

// Initialize Firebase
firebase.initializeApp(firebaseConfig);

// Initialize services
const auth = firebase.auth();
const db = firebase.firestore();
const analytics = firebase.analytics();

console.log('✅ Firebase initialized successfully');
console.log('📊 Project ID:', firebaseConfig.projectId);

// Export for use in other files
window.firebaseAuth = auth;
window.firebaseDb = db;
